# Tasca M3 01
## Exercici 1
### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [95]:
import numpy as np
import pandas as pd
arr= np.array([[1, 2, 3], [4, 5, 6]])
def funcio_dimensió(arr):
    
    if arr.ndim==1:
        df= pd.DataFrame(arr)
        print('number of dimensions :', arr.ndim, df.describe())
    else:
        print ("ERROR")
        
funcio_dimensió(arr)

ERROR


In [119]:
arr = np.array([2,4,6,8,10,12,14,16])
def funcio_dades(arr):
    if arr.ndim==1:
        df=pd.DataFrame(arr) 
        print('number of dimensions :', arr.ndim, df.describe())
    else:
        print ("ERROR")
        
funcio_dades(arr)

number of dimensions : 1                0
count   8.000000
mean    9.000000
std     4.898979
min     2.000000
25%     5.500000
50%     9.000000
75%    12.500000
max    16.000000


## Exercici 2
### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [63]:
from random import randint
def plenar_matriu(n):
    matriu =[]
    for i in range(n):
        fila=[]
        for r in range(n):
            fila.append(randint(0,100))
        matriu.append(fila)
    return matriu    
resultat= plenar_matriu(5)  
print(resultat)

[[34, 98, 9, 57, 74], [78, 98, 7, 46, 56], [72, 57, 67, 3, 20], [29, 28, 38, 2, 10], [6, 45, 50, 44, 80]]


## Exercici 3
### Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [84]:
M1 =np.array([[4,6,8,10,12], [3,5,7,9,11], [10,20,33,44,55]])
print(M1)
def Sumes(M1):
    df= pd.DataFrame(M1)
print("Total columnes",M1.sum(axis=0))
print("Total files",M1.sum(axis=1))
Sumes(M1)

[[ 4  6  8 10 12]
 [ 3  5  7  9 11]
 [10 20 33 44 55]]
Total columnes [17 31 48 63 78]
Total files [ 40  35 162]


In [85]:
print(np.corrcoef(M1))

[[1.         1.         0.99938499]
 [1.         1.         0.99938499]
 [0.99938499 0.99938499 1.        ]]


## Exercici 4
### Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [134]:
print(np.corrcoef(x,y))

[[ 1.         -0.83862787]
 [-0.83862787  1.        ]]


In [140]:
x=np.array([8,2,4])
y=np.array ([12,42,52])
def COEFCOR(x,y):
    if (len(x)!=len(y)):
        print("No tenen la mateixa dimensió")
    else:                        #calculs Numerador
        xmd= np.mean(x)     
        ymd=np.mean(y)
        xi=np.subtract(x,xmd)
        yi=np.subtract(y,ymd)
        mult_xiyi=np.multiply(xi,yi)
        Total_suma=np.sum(mult_xiyi)
        Numerador=Total_suma/len(mult_xiyi)
        
                                #Calculs Denominador
        desv_x=np.std(x)
        desv_y=np.std(y)
        Denominador=np.multiply(desv_x,desv_y)
        
        r=Numerador/Denominador
    return r

COEFCOR(x,y)
    

-0.8386278693775346

##### La correlació lineal es un metode que permet quantificar la relació lineal existent entre 2 variables. Aconsegueix demostrar la relació entre dues o més variables, mesurant el nivell de dependència duna variable respecte duna altra variable independent.
##### Interpretació del valor de l'índex de correlació. Aquest varia en l'interval [-1,1], establint el signe el sentit de la relació, i la interpretació de cada resultat és el següent:
#####  Un valor de 0 indica que no hi ha cap associació entre les dues variables. Un valor més gran que 0 indica una associació positiva. És a dir, a mesura que augmenta el valor d‟una variable, també ho fa el valor de l‟altra. Una correlació negativa (inversa) es produeix quan el coeficient de correlació és inferior a 0. Això és una indicació que les dues variables es mouen a la direcció oposada. 